### ISSUE TITLE
add profile pic for Kommissar Rex

### ISSUE THREAD

**Issue by robinwersich** [EatingBacon/gameprog-detective-server#79]
not strictly necessary, but adds a nice touch imo and should take no more than 5min

**Comment by EatingBacon** [comment]
done

**Comment by EatingBacon** [comment]
![image](https://user-images.githubusercontent.com/33292335/77797771-f018e480-7071-11ea-825f-91ecd6e2d2a3.png)

**Comment by robinwersich** [comment]
nice!
why does he talk about the mensa? ^^

**Comment by EatingBacon** [comment]
Really old conversation from earlier story stages

**Comment by robinwersich** [comment]
lol, the profile pic changes also there, nevermind ^^
