### ISSUE TITLE
Abgabe Mail Korrektur

### ISSUE THREAD

**Issue by EatingBacon** [EatingBacon/gameprog-detective-server#92]

**Comment by ADimeo** [comment]
- The stuff that Tim is ignoring

**Comment by ADimeo** [comment]
otherwise passt's.

**Comment by ADimeo** [comment]
typo: hintersich zu lassen -> hinter sich zu lassen
typo Installationsanw**esiu**ngen

please add reference to https://hpi.de/studium/lehrveranstaltungen/it-systems-engineering-ma/lehrveranstaltung/wise-19-20-2889-game-programming.html  in both projects "about".

**Comment by EatingBacon** [comment]
typo Hilfsko**m**missar

**Comment by robinwersich** [comment]
firebase Url fehlt

**Comment by EatingBacon** [comment]
> firebase Url fehlt

https://us-central1-detectivegame-1053a.cloudfunctions.net ? @Paulpanther ?

**Comment by Paulpanther** [comment]
> > firebase Url fehlt
> 
> https://us-central1-detectivegame-1053a.cloudfunctions.net ? @Paulpanther ?

Korrekt

**Comment by Paulpanther** [comment]
Vielen Dank für die ~Organistaion~Organisation des Seminars, **es** hat uns wirklich Freude bereitet

**Comment by Paulpanther** [comment]
Verlinke bitte auch in das Readme von der App und Bot

**Comment by Paulpanther** [comment]
"sodass zum Losspielen nur noch die **App** aufs Handy geladen werden muss" -> Hier Link zum aktuellen App Release

**Comment by timgarrels** [comment]
"Wir gratulieren Ihnen zu Ihrer Beförderung zum Hilfskommissar! Anbei finden Sie die Tools, die Sie benötigen, um mit Ihrem neuen Vorgesetzten Hauptkommissar Rex in Verbindung zu treten"

Diesen Brief fanden die Betreuer des GameProg Seminars kurz vor der Abgabefrist auf Ihrem Schreibtisch. Endlich, eine Beförderung! Hatten Sie doch schon lange davon geträumt, ihre akademische Laufbahn hinter sich zu lassen und Detektiv zu werden. Dem Brief lag eine Akte bei:


https://github.com/ADimeo/gameprog-detective-app
https://github.com/EatingBacon/gameprog-detective-bot
https://github.com/EatingBacon/gameprog-detective-server


Die drei Repos enthalten sämtlichen Code unserer Abgabe (Man beachte auch das Release "Abgabe" in jedem der drei Repos). Im README des Server Repos findet sich ein kurzes Intro zum Projekt und die Installationsanweisungen für den Server. Die Installationsanweisungen für Bot und App sind in den READMEs der jeweiligen Repos zu finden.
Ausführliche Dokumentation der API, der Datenstrukturen und einige der Spielinteraktionen sind im Wiki zu finden.


Außerdem ist auf dem bereitgestellten Server (ssh root@, Password: ) die aktuelle Instanz der Servers- und der Botkomponente deployed, sodass zum Losspielen nur noch die App aufs Handy geladen werden muss. (Achtung: Server- und Botkomponente sind nicht im Autostart. Ein Reboot des Servers macht einen Neustart beider Komponenten notwendig)

Für die Konfiguration (auch in den Repos dokumentiert) benötigt man ein TelegramBot Token, die IP der Serverkomponente und eine Firebase URL. Im Abgabeserver sind diese bereits konfiguriert, falls ihr einen eigenen Bot und eine eigene IP möchtet, benötigt ihr dafür die folgende Firebase URL: https://us-central1-detectivegame-1053a.cloudfunctions.net

Vielen Dank für die Organisation des Seminars, es hat uns wirklich Freude bereitet
Tim Garrels
Im Namen von Antonio Dimeo, Paul Methfessel, Robin Wersich

**Comment by Paulpanther** [comment]
~C~**K**onfiguration    
konfiguriert, fall**s** ihr ...   
Wenn du unseren Nachnamen mit schreibts, dann verwende auch deinen
